[package]
name = "bevy_handy_extras"
version = "0.3.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.14.0"
bevy_hierarchy = "0.14.0"
bevy_math = "0.14.0"
bevy_state = "0.14.0"
bevy_transform = "0.14.0"
